// GRPO / RULER (split-GPU RL): generate the managed train / infer(vLLM) / orch /
// judge configs and build the `surogate grpo` invocation with a GPU-role split.
// Ported from jackalope's launch.ts.

pub const STUDENT_PORT: u32 = 8007;
pub const JUDGE_PORT: u32 = 8001;
pub const RL_ENV_ID: &str = "markdown-table-qa";

const HEADER: &str = "# generated by jackalope-desktop — regenerated on each launch; edit a copy for custom configs\n";

pub fn train_yaml() -> String {
    format!(
        "{HEADER}model: Qwen/Qwen3-0.6B\noutput_dir: ./outputs\nper_device_train_batch_size: 1\n\
         sequence_len: 2048\nmax_steps: 20\nlogging_steps: 1\nlearning_rate: 1e-4\n\
         lr_scheduler_type: constant\nwarmup_steps: 0\nmax_grad_norm: 1.0\nweight_decay: 0.01\n\
         optimizer: adamw\nrecipe: bf16\nlora: true\nlora_rank: 16\nlora_alpha: 32\n\
         lora_target_modules: [q_proj, k_proj, v_proj, o_proj, gate_proj, up_proj, down_proj]\n\
         save_steps: 100\nreport_to: [surogate]\n"
    )
}

pub fn infer_yaml(port: u32) -> String {
    format!(
        "{HEADER}model: Qwen/Qwen3-0.6B\nenable_lora: true\nmax_lora_rank: 32\n\
         max_model_len: 2048\ngpu_memory_utilization: 0.3\nport: {port}\n"
    )
}

fn env_block(env_path: Option<&str>) -> String {
    match env_path {
        Some(p) => format!("env:\n  - id: {RL_ENV_ID}\n    path: {p}\n"),
        None => format!("env:\n  - id: {RL_ENV_ID}\n"),
    }
}

pub fn grpo_orch_yaml(env_path: Option<&str>) -> String {
    format!(
        "{HEADER}model:\n  name: Qwen/Qwen3-0.6B\n  lora_adapter: default\n  lora_rank: 16\n  lora_alpha: 32\n\
         {env}batch_size: 128\nrollouts_per_example: 16\nseq_len: 2048\nmax_steps: 20\n\
         use_token_client: false\nsampling:\n  max_tokens: 128\nclient:\n  base_url:\n    - http://localhost:{port}/v1\n\
         dump_metrics: true\n",
        env = env_block(env_path),
        port = STUDENT_PORT,
    )
}

pub fn ruler_orch_yaml(env_path: Option<&str>) -> String {
    format!(
        "{HEADER}model:\n  name: Qwen/Qwen3-0.6B\n  lora_adapter: default\n{env}client:\n  base_url:\n    - http://localhost:{sp}/v1\n\
         batch_size: 16\nrollouts_per_example: 4\nseq_len: 2048\nmax_steps: 20\nuse_token_client: false\n\
         sampling:\n  max_tokens: 256\nverification:\n  enabled: true\nruler:\n  enabled: true\n  mode: replace\n\
           judge_model: \"Qwen/Qwen3-1.7B\"\n  judge:\n    base_url:\n      - http://localhost:{jp}/v1\n\
             api_key_var: RULER_JUDGE_API_KEY\n    timeout: 90.0\n  weight: 1.0\n  max_concurrent_judges: 8\n\
           sampling:\n    temperature: 0.0\n    max_completion_tokens: 4096\n  extra_body:\n    chat_template_kwargs:\n      enable_thinking: false\n\
           swallow_exceptions: true\ndump_metrics: true\n",
        env = env_block(env_path),
        sp = STUDENT_PORT,
        jp = JUDGE_PORT,
    )
}

pub fn judge_yaml(port: u32) -> String {
    format!(
        "{HEADER}model: Qwen/Qwen3-1.7B\nenable_lora: false\nmax_model_len: 4096\n\
         gpu_memory_utilization: 0.3\nport: {port}\n"
    )
}

/// Build the `surogate grpo …` argv with the GPU-role split. `judge_*` are used
/// only for RULER. Pure → testable.
pub fn build_grpo_args(
    train: &str,
    infer: &str,
    orch: &str,
    trainer_gpus: &[u32],
    vllm_gpus: &[u32],
    judge: Option<&str>,
    judge_gpus: &[u32],
) -> Vec<String> {
    let join = |g: &[u32]| g.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(",");
    let mut a = vec![
        "grpo".into(),
        "--train".into(), train.into(),
        "--infer".into(), infer.into(),
        "--orch".into(), orch.into(),
        "--trainer-gpus".into(), join(trainer_gpus),
        "--vllm-gpus".into(), join(vllm_gpus),
    ];
    if let Some(j) = judge {
        if !judge_gpus.is_empty() {
            a.push("--judge-infer".into());
            a.push(j.into());
            a.push("--judge-gpus".into());
            a.push(join(judge_gpus));
        }
    }
    a
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn grpo_args_have_roles() {
        let a = build_grpo_args("t.yaml", "i.yaml", "o.yaml", &[0], &[1], None, &[]);
        assert!(a.contains(&"grpo".to_string()));
        assert!(a.windows(2).any(|w| w == ["--trainer-gpus", "0"]));
        assert!(a.windows(2).any(|w| w == ["--vllm-gpus", "1"]));
        assert!(!a.iter().any(|x| x == "--judge-infer"));
    }

    #[test]
    fn ruler_args_add_judge() {
        let a = build_grpo_args("t", "i", "o", &[0], &[1], Some("j.yaml"), &[2]);
        assert!(a.windows(2).any(|w| w == ["--judge-infer", "j.yaml"]));
        assert!(a.windows(2).any(|w| w == ["--judge-gpus", "2"]));
    }

    #[test]
    fn yamls_have_expected_keys() {
        assert!(train_yaml().contains("report_to: [surogate]"));
        assert!(infer_yaml(8007).contains("port: 8007"));
        assert!(grpo_orch_yaml(Some("/repo/env")).contains("path: /repo/env"));
        assert!(ruler_orch_yaml(None).contains("judge_model: \"Qwen/Qwen3-1.7B\""));
        assert!(judge_yaml(8001).contains("port: 8001"));
    }
}
